import { LevelDefinition } from './ProgressionState.ts';

/**
 * 75 NIVELES CRONOLÓGICOS - 75 AÑOS DE HISTORIA REAL DE ARCOR (1951 - 2025)
 * Datos rigurosamente verificados con hitos históricos documentados,
 * niveles especiales festivos, pistas de anticipación (1-3 niveles antes)
 * y una curva de dificultad perfectamente equilibrada.
 */
export const SAGA_LEVELS: LevelDefinition[] = [
  {
    levelNumber: 1,
    title: "Nivel 1: Fundación de Arcor, 1951",
    year: 1951,
    decadeTitle: "Años 50: El Nacimiento",
    xPercent: 9.5,
    yPercent: 33.2,
    description: "Don Fulvio Pagani y sus jóvenes socios encienden la primera paila de cobre en Arroyito, Córdoba.",
    quote: "Dar a todos caramelos de calidad a un precio justo para que la dulzura llegue a cada hogar.",
    targetCandies: ["caramelo_1951","minty","caramelo_miel"],
    eraTag: "🏭 NACIMIENTO DE ARCOR",
    storyHeadline: "¡Estás en el año 1951 y nace el sueño en Arroyito!",
    storyBody: "El 5 de julio de 1951, Fulvio Salvador Pagani, junto a sus hermanos Renzo y Elio, y amigos pioneros (Maranzana, Seveso y Brizio), inauguran un modesto taller para producir 5.000 kg diarios de caramelos artesanales.",
    funFact: "El nombre ARCOR nació de unir las dos primeras letras de ARroyito y las tres de CÓRdoba.",
    isSpecialMilestone: true,
    milestoneTitle: "Fundación de ARCOR en Arroyito"
  },
  {
    levelNumber: 2,
    title: "Nivel 2: Los Primeros Confiteros, 1952",
    year: 1952,
    decadeTitle: "Años 50: El Primer Taller",
    xPercent: 11.8,
    yPercent: 33,
    description: "Se suman maestros artesanos y vecinos de Arroyito para responder a la creciente demanda.",
    quote: "La fuerza de una empresa nace en el corazón de su pueblo.",
    targetCandies: ["caramelo_1951","minty"],
    eraTag: "🤝 COMUNIDAD DE ARROYITO",
    storyHeadline: "¡Año 1952: el taller de Arroyito late con fuerza!",
    storyBody: "Los vecinos de Arroyito se suman entusiasmados al taller de pailas. Los primeros caramelos duros de menta y miel comienzan a ganar fama en los pueblos cercanos.",
    funFact: "Los fundadores cargaban personalmente las bolsas de azúcar de 50 kg para encender la cocción.",
    isSpecialMilestone: false,
    hint: "Don Fulvio nota que los carros a caballo tardan demasiado en cruzar las huellas... algo sobre ruedas se prepara."
  },
  {
    levelNumber: 3,
    title: "Nivel 3: El Legendario Camión Verde, 1953",
    year: 1953,
    decadeTitle: "Años 50: Rutas de Córdoba",
    xPercent: 17.3,
    yPercent: 32.6,
    description: "Arcor adquiere su primer camión de reparto para llevar golosinas frescas directo a los almacenes.",
    quote: "Llegar donde otros no llegan, sin intermediarios, para que el producto llegue fresco.",
    targetCandies: ["caramelo_1951","caramelo_miel"],
    eraTag: "🚚 DISTRIBUCIÓN DIRECTA",
    storyHeadline: "¡Año 1953: sale a la ruta el camión verde de Arcor!",
    storyBody: "Para no depender de intermediarios y asegurar que el caramelo llegue impecable a los almacenes de ramos generales, Arcor adquiere su primer camión de reparto propio.",
    funFact: "Aquel legendario camión Ford verde de 1953 fue totalmente restaurado y hoy se exhibe en el Museo Arcor.",
    isSpecialMilestone: true,
    milestoneTitle: "El Primer Camión de Reparto Propio"
  },
  {
    levelNumber: 4,
    title: "Nivel 4: Rutas hacia el Litoral, 1954",
    year: 1954,
    decadeTitle: "Años 50: Expansión Regional",
    xPercent: 22.7,
    yPercent: 32.2,
    description: "Las golosinas cordobesas conquistan Santa Fe y Entre Ríos.",
    quote: "El dulce no conoce fronteras provinciales.",
    targetCandies: ["caramelo_1951","minty"],
    eraTag: "🗺️ EXPANDIENDO HORIZONTES",
    storyHeadline: "¡Año 1954: el sabor de Arroyito cruza a Santa Fe!",
    storyBody: "Los almaceneros reciben con alegría las latas de caramelos Arcor. La red de distribución propia demuestra ser una ventaja imbatible.",
    funFact: "En 1954 se producían ya más de 12.000 kg diarios de caramelos.",
    isSpecialMilestone: false
  },
  {
    levelNumber: 5,
    title: "Nivel 5: Nuevas Pailas y Calderas, 1955",
    year: 1955,
    decadeTitle: "Años 50: Mecanización",
    xPercent: 25,
    yPercent: 32,
    description: "Modernización del taller con calderas continuas de vapor.",
    quote: "El fuego y el vapor trabajan para dar brillo al caramelo cristalino.",
    targetCandies: ["caramelo_1951","caramelo_frutal"],
    eraTag: "⚙️ PRIMERAS MÁQUINAS",
    storyHeadline: "¡Año 1955: calderas de vapor en acción!",
    storyBody: "Se instalan calderas automáticas que mantienen el punto exacto de hervor del almíbar, garantizando transparencia cristalina y textura crocante.",
    funFact: "El vapor de agua redujo a la mitad el tiempo de cocción de cada tanda de almíbar.",
    isSpecialMilestone: false
  },
  {
    levelNumber: 6,
    title: "Nivel 6: Cítricos y Frutas del Valle, 1956",
    year: 1956,
    decadeTitle: "Años 50: Sabores Frutales",
    xPercent: 26.9,
    yPercent: 32.1,
    description: "Se incorporan pulpas y esencias naturales de limón, naranja y mandarina.",
    quote: "La fruta de nuestra tierra combinada con el azúcar más puro.",
    targetCandies: ["caramelo_1951","minty","caramelo_frutal"],
    eraTag: "🍋 SABORES DEL CAMPO",
    storyHeadline: "¡Año 1956: llegan los caramelos frutales cítricos!",
    storyBody: "Arcor amplía su paleta de sabores con esencias cítricas naturales. Los caramelos ácidos y dulces se convierten en los preferidos de los recreos.",
    funFact: "Las recetas originales de 1956 utilizaban limones y naranjas cosechados en el valle cordobés.",
    isSpecialMilestone: false,
    hint: "La glucosa de proveedores externos empieza a escasear... Don Fulvio mira los campos de maíz con visión pionera."
  },
  {
    levelNumber: 7,
    title: "Nivel 7: El Sueño del Autoabastecimiento, 1957",
    year: 1957,
    decadeTitle: "Años 50: Víspera de la Integración",
    xPercent: 31.7,
    yPercent: 32.3,
    description: "Ingenieros y técnicos proyectan la molienda húmeda de maíz.",
    quote: "Para no depender de nadie, debemos ser dueños de nuestros propios insumos.",
    targetCandies: ["caramelo_1951","minty","caramelo_miel"],
    eraTag: "🌽 PLANIFICANDO EL MAÍZ",
    storyHeadline: "¡Año 1957: los planos de la gran planta de glucosa!",
    storyBody: "Frente a las crisis de abastecimiento de glucosa en el país, Don Fulvio y el equipo deciden dar el paso más audaz: moler su propio maíz para extraer almidón y jarabe.",
    funFact: "En 1957 se aprobó el proyecto que cambiaría la historia industrial de la empresa.",
    isSpecialMilestone: false,
    hint: "Los cimientos de hormigón se levantan junto a las vías... Arroyito se convertirá en un gigante de la glucosa."
  },
  {
    levelNumber: 8,
    title: "Nivel 8: La Gran Molienda de Maíz, 1958",
    year: 1958,
    decadeTitle: "Años 50: Hito de la Integración",
    xPercent: 37.8,
    yPercent: 32.7,
    description: "Se inaugura la molienda de maíz en Arroyito y la fábrica alcanza 60.000 kg diarios de golosinas.",
    quote: "La integración vertical es la garantía absoluta de pureza, calidad y costo justo.",
    targetCandies: ["caramelo_1951","minty","caramelo_frutal"],
    eraTag: "🌽 INTEGRACIÓN VERTICAL",
    storyHeadline: "¡Año 1958: Arcor alcanza 60.000 kg diarios y muele su propio maíz!",
    storyBody: "Nace la legendaria integración vertical de Arcor: la fábrica de Arroyito procesa maíz cordobés para obtener su propia glucosa y almidón. La producción salta a la impresionante cifra de 60.000 kg diarios.",
    funFact: "Arcor fue la primera confitería industrial de Sudamérica en producir su propia glucosa.",
    isSpecialMilestone: true,
    milestoneTitle: "Integración Vertical: Molienda de Maíz y 60.000 kg"
  },
  {
    levelNumber: 9,
    title: "Nivel 9: Liderazgo Nacional en Dulzura, 1959",
    year: 1959,
    decadeTitle: "Años 50: Cierre de la Década Fundacional",
    xPercent: 42.6,
    yPercent: 32.9,
    description: "Cierra la década del 50 con Arcor como referente indiscutido en caramelos.",
    quote: "En ocho años pasamos de una modesta paila al liderazgo nacional.",
    targetCandies: ["caramelo_1951","minty","caramelo_miel"],
    eraTag: "⭐ DÉCADA FUNDACIONAL",
    storyHeadline: "¡Año 1959: el sueño de 1951 se ha hecho realidad!",
    storyBody: "Al terminar la década del 50, Arcor es sinónimo de caramelos en toda Argentina. La fábrica de Arroyito no duerme y el ferrocarril despacha vagones enteros de dulzura.",
    funFact: "En 1959 ya trabajaban más de 300 familias de Arroyito en el complejo industrial.",
    isSpecialMilestone: false
  },
  {
    levelNumber: 10,
    title: "Nivel 10: Toffees en Barra, 1960",
    year: 1960,
    decadeTitle: "Años 60: La Nueva Década",
    xPercent: 44.5,
    yPercent: 33,
    description: "Lanzamiento de las barras de toffee de dulce de leche suave.",
    quote: "El dulce de leche argentino transformado en una joya confitera.",
    targetCandies: ["toffee_cubo","caramelo_1951"],
    eraTag: "🧈 TOFFEE TRADICIONAL",
    storyHeadline: "¡Año 1960: nacen los toffees en barra!",
    storyBody: "Con leche fresca de tambos de la cuenca lechera cordobesa, Arcor perfecciona la cocción de toffees suaves. Nace un producto que enamora a varias generaciones.",
    funFact: "La leche condensada se cocinaba lentamente con azúcar pura y manteca de primera calidad.",
    isSpecialMilestone: true,
    milestoneTitle: "Fábrica de Glucosa Lules & Toffees en Barra"
  },
  {
    levelNumber: 11,
    title: "Nivel 11: Depósitos en Buenos Aires, 1961",
    year: 1961,
    decadeTitle: "Años 60: Red Logística",
    xPercent: 48,
    yPercent: 35.5,
    description: "Inauguración de grandes centros logísticos en la capital del país.",
    quote: "Conectar Arroyito con los puertos y las grandes metrópolis.",
    targetCandies: ["caramelo_1951","minty"],
    eraTag: "🏢 CENTROS LOGÍSTICOS",
    storyHeadline: "¡Año 1961: desembarco masivo en Buenos Aires!",
    storyBody: "Los caramelos de Arroyito llegan a los quioscos porteños, estaciones de tren y tiendas de golosinas de todo el Gran Buenos Aires con entrega diaria garantizada.",
    funFact: "La flota propia de camiones ya superaba las 25 unidades recorriendo el territorio nacional.",
    isSpecialMilestone: false
  },
  {
    levelNumber: 12,
    title: "Nivel 12: Laboratorio de Calidad, 1962",
    year: 1962,
    decadeTitle: "Años 60: Calidad y Precisión",
    xPercent: 49,
    yPercent: 39,
    description: "Instalación de laboratorios químicos para control de pureza y humedad.",
    quote: "La excelencia no se presume, se mide y comprueba en cada caramelo.",
    targetCandies: ["caramelo_1951","toffee_cubo"],
    eraTag: "🔬 CONTROL DE CALIDAD",
    storyHeadline: "¡Año 1962: química y ciencia al servicio del sabor!",
    storyBody: "Se inaugura el laboratorio de bromatología en Arroyito para testear cada lote de almíbar, garantizando consistencia inalterable frente al calor y la humedad.",
    funFact: "Arcor implementó normas de control microbiológico pioneras en la industria alimenticia argentina.",
    isSpecialMilestone: false,
    hint: "Cartas comerciales con sellos de ultramar llegan al escritorio de Don Fulvio... el mundo quiere caramelos argentinos."
  },
  {
    levelNumber: 13,
    title: "Nivel 13: Negociaciones de Exportación, 1963",
    year: 1963,
    decadeTitle: "Años 60: Víspera Exportadora",
    xPercent: 46.5,
    yPercent: 41.3,
    description: "Preparación de envoltorios bilingües y acuerdos de flete marítimo.",
    quote: "Los caramelos de Arroyito listos para cruzar los océanos.",
    targetCandies: ["caramelo_1951","minty"],
    eraTag: "🌐 RUMBO A ULTRAMAR",
    storyHeadline: "¡Año 1963: preparando la primera travesía transatlántica!",
    storyBody: "Se rediseñan empaques para cumplir estándares internacionales. Los primeros cargamentos de muestra viajan a distribuidores de Estados Unidos y Europa.",
    funFact: "Los importadores extranjeros quedaron fascinados por la relación calidad-precio de Arcor.",
    isSpecialMilestone: false,
    hint: "Maquinarias modernas de envoltura continua llegan al puerto de Buenos Aires desde Europa."
  },
  {
    levelNumber: 14,
    title: "Nivel 14: Salto al Comercio Exterior, 1964",
    year: 1964,
    decadeTitle: "Años 60: Hito Exportador",
    xPercent: 44,
    yPercent: 43.5,
    description: "Primeras exportaciones a Estados Unidos e incorporación de máquinas envolvedoras automáticas.",
    quote: "Cuando se trabaja con seriedad y pasión, el mundo entero abre sus puertas.",
    targetCandies: ["caramelo_1951","toffee_cubo","minty"],
    eraTag: "🚢 PRIMERAS EXPORTACIONES",
    storyHeadline: "¡Año 1964: Arcor exporta por primera vez a los Estados Unidos!",
    storyBody: "En 1964, Arcor concreta su primera exportación oficial a Estados Unidos. Al mismo tiempo, se incorporan envolvedoras automáticas de alta velocidad que envuelven cientos de caramelos por minuto.",
    funFact: "Las máquinas automáticas envolvían en 60 segundos lo que a mano tomaba horas enteras de trabajo artesanal.",
    isSpecialMilestone: true,
    milestoneTitle: "Primeras Exportaciones y Envolvedoras Automáticas"
  },
  {
    levelNumber: 15,
    title: "Nivel 15: La Conquista de las Ferias, 1965",
    year: 1965,
    decadeTitle: "Años 60: Ferias Internacionales",
    xPercent: 40.3,
    yPercent: 45,
    description: "Arcor se destaca en la Feria Internacional de Dulces de Colonia, Alemania.",
    quote: "Competir de igual a igual con los maestros confiteros del Viejo Mundo.",
    targetCandies: ["caramelo_1951","minty"],
    eraTag: "🏆 FERIAS DEL MUNDO",
    storyHeadline: "¡Año 1965: Arroyito brilla en Colonia, Alemania!",
    storyBody: "Los caramelos cristalinos y de menta de Arcor reciben aplausos en las ferias europeas. Distribuidores de América Latina solicitan contratos de representación exclusiva.",
    funFact: "Don Fulvio Pagani regresó de Colonia con pedidos de más de diez países distintos.",
    isSpecialMilestone: false
  },
  {
    levelNumber: 16,
    title: "Nivel 16: Gasoducto y Energía Propia, 1966",
    year: 1966,
    decadeTitle: "Años 60: Gas e Infraestructura",
    xPercent: 36.5,
    yPercent: 46.5,
    description: "Construcción de obras de gas natural y suministro eléctrico en Arroyito.",
    quote: "Sin energía confiable no hay futuro industrial posible.",
    targetCandies: ["caramelo_1951","toffee_cubo"],
    eraTag: "⚡ ENERGÍA Y GAS",
    storyHeadline: "¡Año 1966: gasoducto industrial en Arroyito!",
    storyBody: "Para alimentar los hornos de cocción continua sin interrupciones, Arcor colabora en la construcción del gasoducto y subestaciones eléctricas para toda la región.",
    funFact: "Esta obra benefició no solo a la fábrica sino a miles de hogares del pueblo de Arroyito.",
    isSpecialMilestone: false
  },
  {
    levelNumber: 17,
    title: "Nivel 17: Línea de Caramelos Masticables, 1967",
    year: 1967,
    decadeTitle: "Años 60: Caramelos Masticables",
    xPercent: 31.8,
    yPercent: 48.5,
    description: "Nuevas recetas de caramelos tiernos masticables con jugo frutal.",
    quote: "Suavidad que se mastica y sabor que perdura.",
    targetCandies: ["caramelo_1951","minty","toffee_cubo"],
    eraTag: "🍬 MASTICABLES TIERNOS",
    storyHeadline: "¡Año 1967: nacen los caramelos masticables!",
    storyBody: "Se introducen batidoras especiales para airear el almíbar con glucosa, logrando la textura masticable esponjosa que revoluciona las cantinas escolares.",
    funFact: "Fueron los antecesores directos de los populares caramelos masticables Arcor de hoy.",
    isSpecialMilestone: false,
    hint: "Contratos millonarios con cadenas de supermercados estadounidenses están a punto de firmarse."
  },
  {
    levelNumber: 18,
    title: "Nivel 18: La Conquista del Mercado de EE.UU., 1968",
    year: 1968,
    decadeTitle: "Años 60: El Salto Americano",
    xPercent: 27,
    yPercent: 50.5,
    description: "Exportaciones a gran escala a las principales cadenas de Estados Unidos.",
    quote: "La constancia cordobesa compite en las góndolas más exigentes del planeta.",
    targetCandies: ["caramelo_1951","toffee_cubo","minty"],
    eraTag: "🇺🇸 MERCADO DE EE.UU.",
    storyHeadline: "¡Año 1968: cargamentos masivos rumbo a los puertos norteamericanos!",
    storyBody: "Arcor consolida un flujo continuo de exportación a Estados Unidos. Millones de caramelos argentinos se consumen en las costas este y oeste norteamericanas.",
    funFact: "En 1968, Arcor se consagró como el principal exportador argentino de golosinas elaboradas.",
    isSpecialMilestone: true,
    milestoneTitle: "Consolidación Exportadora en Estados Unidos",
    hint: "En Arroyito se proyecta un laboratorio secreto... el aroma a cacao tostado empieza a sentirse."
  },
  {
    levelNumber: 19,
    title: "Nivel 19: Proyectos de Chocolate y Galletas, 1969",
    year: 1969,
    decadeTitle: "Años 60: Víspera del Gran Salto Multiproducto",
    xPercent: 24.6,
    yPercent: 51.6,
    description: "Planificación de las nuevas plantas de chocolatería y galletería.",
    quote: "Dejar de ser solo una fábrica de caramelos para ser un imperio alimentario.",
    targetCandies: ["caramelo_1951","toffee_cubo"],
    eraTag: "🍫 VÍSPERA DEL CHOCOLATE",
    storyHeadline: "¡Año 1969: hacia la era del chocolate y las galletitas!",
    storyBody: "Don Fulvio reúne al directorio para aprobar el plan maestro de los 70: ingresar con fuerza a la chocolatería fina y a las galletitas para acompañar el desayuno familiar.",
    funFact: "Los fundadores viajaron a Suiza y Bélgica para seleccionar las mejores tecnologías de refinado de cacao.",
    isSpecialMilestone: false,
    hint: "En 1970 se encenderán las refinadoras de chocolate y los hornos de galletitas... el salto multiproducto es inminente."
  },
  {
    levelNumber: 20,
    title: "Nivel 20: Nacimiento de Chocolates y Galletitas, 1970",
    year: 1970,
    decadeTitle: "Años 70: Era Multiproducto",
    xPercent: 19.9,
    yPercent: 53.9,
    description: "Arcor se consolida como empresa multiproducto, inaugurando plantas de chocolates y galletas.",
    quote: "El chocolate y la galleta completan la mesa de todos los hogares argentinos.",
    targetCandies: ["aguila","caramelo_1951","toffee_cubo"],
    eraTag: "🍫 EMPRESA MULTIPRODUCTO",
    storyHeadline: "¡Año 1970: Arcor inaugura sus plantas de chocolates y galletitas!",
    storyBody: "Arcor deja de ser solo caramelería: se inaugura la planta de chocolates y de galletas en Arroyito. Nacen los primeros bombones rellenos y masas horneadas con harina propia.",
    funFact: "Desde 1970, el perfume a chocolate recién conchado se convirtió en el sello aromático de Arroyito.",
    isSpecialMilestone: true,
    milestoneTitle: "Empresa Multiproducto: Chocolates y Galletitas"
  },
  {
    levelNumber: 21,
    title: "Nivel 21: Silos y Molienda de Trigo, 1971",
    year: 1971,
    decadeTitle: "Años 70: Harinas y Molinos",
    xPercent: 17.5,
    yPercent: 55,
    description: "Instalación de silos y molinos para asegurar harina seleccionada propia.",
    quote: "El trigo más fino para la masa más crocante.",
    targetCandies: ["aguila","toffee_cubo"],
    eraTag: "🌾 HARINAS SELECCIONADAS",
    storyHeadline: "¡Año 1971: silos y harinas propias para las galletitas!",
    storyBody: "Para asegurar la máxima frescura en la galletería, Arcor construye silos de acopio y molinos de harina fina. La integración vertical suma ahora al trigo.",
    funFact: "Cada silo podía almacenar miles de toneladas de granos de trigo de primera selección pampeana.",
    isSpecialMilestone: false
  },
  {
    levelNumber: 22,
    title: "Nivel 22: Red Oficial de Distribuidores, 1972",
    year: 1972,
    decadeTitle: "Años 70: Red de Distribuidores",
    xPercent: 16,
    yPercent: 58,
    description: "Formalización de la red nacional de distribuidores oficiales de Arcor.",
    quote: "Una alianza de confianza con comerciantes y familias de todo el país.",
    targetCandies: ["caramelo_1951","aguila"],
    eraTag: "🤝 DISTRIBUIDORES OFICIALES",
    storyHeadline: "¡Año 1972: se formaliza la red de distribuidores Arcor!",
    storyBody: "Arcor crea un sistema pionero de distribución asociada: distribuidores independientes en cada provincia que comercializan exclusivamente las marcas de la fábrica.",
    funFact: "Este sistema de distribución se estudia hoy en universidades como modelo logístico ejemplar.",
    isSpecialMilestone: false
  },
  {
    levelNumber: 23,
    title: "Nivel 23: Tecnología de Concheado Fino, 1973",
    year: 1973,
    decadeTitle: "Años 70: Conchadoras Suizas",
    xPercent: 14.5,
    yPercent: 61,
    description: "Llegan conchadoras suizas para elaborar tabletas de chocolate aterciopeladas.",
    quote: "La suavidad que se disuelve en el paladar se logra con paciencia y precisión.",
    targetCandies: ["aguila","toffee_cubo"],
    eraTag: "🇨🇭 CONCHEADO SUIZO",
    storyHeadline: "¡Año 1973: chocolates refinados de clase mundial!",
    storyBody: "Las refinadoras suizas reducen las partículas de cacao y azúcar a menos de 20 micrones, logrando que el chocolate se funda suavemente en la boca sin grumos.",
    funFact: "El proceso de concheado podía durar hasta 72 horas continuas para liberar los aromas nobles del cacao.",
    isSpecialMilestone: false,
    hint: "En el noroeste argentino, el azúcar de caña tucumana llama a una gran alianza industrial."
  },
  {
    levelNumber: 24,
    title: "Nivel 24: Misky S.A. en Tucumán, 1974",
    year: 1974,
    decadeTitle: "Años 70: Expansión Azucarera",
    xPercent: 16.3,
    yPercent: 64,
    description: "Se inaugura la planta industrial de Misky en La Florida, Tucumán.",
    quote: "Integrar el azúcar del norte argentino para abastecer a la fábrica nacional.",
    targetCandies: ["aguila","caramelo_1951","toffee_cubo"],
    eraTag: "🌱 MISKY TUCUMÁN",
    storyHeadline: "¡Año 1974: Arcor inaugura Misky en Tucumán!",
    storyBody: "Arcor inaugura su planta de caramelos y derivados azucareros en Tucumán (Misky S.A.), aprovechando la cercanía con los ingenios azucareros y expandiendo la presencia en el norte del país.",
    funFact: "Misky se transformó en uno de los motores económicos y de empleo más importantes de Tucumán.",
    isSpecialMilestone: true,
    milestoneTitle: "Inauguración de Misky en Tucumán"
  },
  {
    levelNumber: 25,
    title: "Nivel 25: Oficinas en Paraguay y Uruguay, 1975",
    year: 1975,
    decadeTitle: "Años 70: Cono Sur",
    xPercent: 18,
    yPercent: 67,
    description: "Apertura de representaciones comerciales directas en Montevideo y Asunción.",
    quote: "La hermandad del Cono Sur unida por la misma dulzura.",
    targetCandies: ["caramelo_1951","aguila"],
    eraTag: "🇺🇾 PARAGUAY Y URUGUAY",
    storyHeadline: "¡Año 1975: filiales comerciales en Montevideo y Asunción!",
    storyBody: "Arcor establece oficinas comerciales directas en Uruguay y Paraguay, consolidando una red de ventas que abastece a miles de pequeños comercios vecinos.",
    funFact: "Uruguay fue uno de los primeros países en adoptar masivamente los bombones y caramelos de Arcor.",
    isSpecialMilestone: false
  },
  {
    levelNumber: 26,
    title: "Nivel 26: Complejo Industrial San Pedro, 1976",
    year: 1976,
    decadeTitle: "Años 70: Complejo San Pedro",
    xPercent: 22.3,
    yPercent: 67.1,
    description: "Construcción de la planta harinera y de galletas en San Pedro, Buenos Aires.",
    quote: "Ubicación estratégica a orillas del Paraná para despachar al mundo.",
    targetCandies: ["aguila","toffee_cubo"],
    eraTag: "🌾 SAN PEDRO, BS. AS.",
    storyHeadline: "¡Año 1976: planta industrial de San Pedro!",
    storyBody: "En una ubicación privilegiada sobre el corredor industrial bonaerense, Arcor levanta la planta de San Pedro para la molienda de trigo y fabricación de productos horneados.",
    funFact: "San Pedro contaba con acceso directo a autopistas y al río Paraná para abaratar fletes.",
    isSpecialMilestone: false
  },
  {
    levelNumber: 27,
    title: "Nivel 27: Envoltorios de Alta Barrera, 1977",
    year: 1977,
    decadeTitle: "Años 70: Empaques de Vanguardia",
    xPercent: 26.5,
    yPercent: 67.2,
    description: "Innovación en películas de envoltura metalizada para climas extremos.",
    quote: "Proteger el bombón para que conserve su brillo en cualquier rincón del planeta.",
    targetCandies: ["aguila","caramelo_1951"],
    eraTag: "✨ EMPAQUES METALIZADOS",
    storyHeadline: "¡Año 1977: innovación en barreras contra la humedad!",
    storyBody: "Se desarrollan películas bicapa de polipropileno para proteger los chocolates y caramelos de la humedad y el calor de exportación.",
    funFact: "Esto permitió que los productos llegaran perfectos a climas tropicales de Centroamérica y el Caribe.",
    isSpecialMilestone: false
  },
  {
    levelNumber: 28,
    title: "Nivel 28: El Gran Puente sobre el Río Suquía, 1978",
    year: 1978,
    decadeTitle: "Años 70: El Puente de Arroyito",
    xPercent: 27.5,
    yPercent: 69.3,
    description: "Construcción del puente vial que conecta la fábrica con las rutas nacionales.",
    quote: "Un puente une orillas, conecta pueblos y abre caminos al progreso.",
    targetCandies: ["caramelo_1951","aguila","toffee_cubo"],
    eraTag: "🌉 EL PUENTE HISTÓRICO",
    storyHeadline: "¡Año 1978: se inaugura el puente vial de Arroyito!",
    storyBody: "Para agilizar la salida constante de camiones de carga, se construye el gran puente sobre el río Suquía, integrando definitivamente el complejo fabril con la Ruta Nacional 19.",
    funFact: "El puente sigue siendo hoy una postal emblemática de la ciudad de Arroyito.",
    isSpecialMilestone: false,
    hint: "El costo y retraso de las cajas de cartón ajenas preocupa a Don Fulvio... una fábrica de papel propia es el plan."
  },
  {
    levelNumber: 29,
    title: "Nivel 29: El Proyecto de Cartón Corrugado, 1979",
    year: 1979,
    decadeTitle: "Años 70: Víspera de Cartocor",
    xPercent: 28.5,
    yPercent: 71.5,
    description: "Montaje de las máquinas corrugadoras para fabricar cajas de empaque.",
    quote: "Una caja resistente cuida la dulzura que tanto esfuerzo costó crear.",
    targetCandies: ["aguila","toffee_cubo"],
    eraTag: "📦 PROYECTO CARTOCOR",
    storyHeadline: "¡Año 1979: las primeras pruebas de cartón corrugado!",
    storyBody: "Técnicos especializados ensamblan en Arroyito la primera máquina corrugadora continua. Arcor decide producir sus propios envases de cartón.",
    funFact: "En 1979 se hicieron las primeras cajas experimentales con papel kraft argentino.",
    isSpecialMilestone: false,
    hint: "1980 marcará un doble hito: nacerá Cartocor y Arcor comprará su primera fábrica en Brasil."
  },
  {
    levelNumber: 30,
    title: "Nivel 30: Cartocor S.A. y Desembarco en Brasil, 1980",
    year: 1980,
    decadeTitle: "Años 80: Nacimiento de Cartocor",
    xPercent: 24.8,
    yPercent: 74,
    description: "Se funda Cartocor para producir cartón corrugado y se adquiere Nechar en San Pablo, Brasil.",
    quote: "Autoabastecernos de envases y cruzar las fronteras para fabricar en el hermano país.",
    targetCandies: ["aguila","toffee_cubo","caramelo_1951"],
    eraTag: "📦 CARTOCOR Y BRASIL",
    storyHeadline: "¡Año 1980: nace Cartocor y primera fábrica en Brasil!",
    storyBody: "Nace Cartocor en Arroyito para elaborar cajas de cartón corrugado para Arcor y terceros. Al mismo tiempo, Arcor adquiere Nechar Alimentos en San Pablo: su primera fábrica fuera de Argentina.",
    funFact: "Cartocor se convertiría con los años en el mayor fabricante de cartón corrugado del país.",
    isSpecialMilestone: true,
    milestoneTitle: "Creación de Cartocor y Llegada a Brasil"
  },
  {
    levelNumber: 31,
    title: "Nivel 31: Envases para la Fruticultura, 1981",
    year: 1981,
    decadeTitle: "Años 80: Cartón para el Mundo",
    xPercent: 21,
    yPercent: 76.5,
    description: "Cartocor comienza a proveer cajas a los exportadores de manzanas y peras del Valle de Río Negro.",
    quote: "El cartón cordobés protege la fruta argentina que viaja por los mares.",
    targetCandies: ["aguila","toffee_cubo"],
    eraTag: "🍎 CARTOCOR EN EL PAÍS",
    storyHeadline: "¡Año 1981: Cartocor abastece a los fruticultores argentinos!",
    storyBody: "La calidad estructural del cartón corrugado de Cartocor resiste cámaras de frío y traslados marítimos. Los exportadores frutícolas lo adoptan masivamente.",
    funFact: "Cartocor diseñó envases ventilados especiales que mantenían la fruta fresca semanas enteras.",
    isSpecialMilestone: false,
    hint: "En el laboratorio de caramelos se experimenta con almidón y jugos cítricos para una golosina divertida..."
  },
  {
    levelNumber: 32,
    title: "Nivel 32: Primeros Prototipos de Gomitas, 1982",
    year: 1982,
    decadeTitle: "Años 80: El Ensayo de las Gomitas",
    xPercent: 18,
    yPercent: 77.8,
    description: "Desarrollo de fórmulas de gelatina natural con formas lúdicas y ositos.",
    quote: "La golosina debe ser un juego alegre para el niño.",
    targetCandies: ["caramelo_1951","toffee_cubo"],
    eraTag: "🐻 ENSAYOS DE GELATINA",
    storyHeadline: "¡Año 1982: nacen los primeros moldes de ositos de gelatina!",
    storyBody: "Se instalan tolvas de almidón donde se estampan los moldes de ositos. Los confiteros prueban concentraciones de jugo natural de manzana, frutilla y naranja.",
    funFact: "Fue el primer desarrollo argentino de golosinas de gelatina con auténtico jugo de fruta concentrado.",
    isSpecialMilestone: false,
    hint: "En 1983 se lanzará la marca más alegre de gomitas de la historia argentina: Mogul."
  },
  {
    levelNumber: 33,
    title: "Nivel 33: Lanzamiento de Mogul, 1983",
    year: 1983,
    decadeTitle: "Años 80: La Revolución Mogul",
    xPercent: 15,
    yPercent: 79,
    description: "Nace Mogul, la primera y más famosa línea de gomitas con jugo de frutas de Argentina.",
    quote: "La ternura masticable que cambió los recreos escolares para siempre.",
    targetCandies: ["mogul","caramelo_1951","toffee_cubo"],
    eraTag: "🐻 NACIMIENTO DE MOGUL",
    storyHeadline: "¡Año 1983: nace Mogul y revoluciona los quioscos!",
    storyBody: "Arcor lanza oficialmente Mogul: gomitas de gelatina con jugo natural de frutas en formas de ositos, tiburones y frutillas. Se convierten al instante en la golosina favorita de los niños.",
    funFact: "Mogul es hasta hoy la marca de gomitas más vendida y querida de Argentina.",
    isSpecialMilestone: true,
    milestoneTitle: "Lanzamiento de Gomitas Mogul",
    hint: "Don Fulvio Pagani trabaja día y noche en un secreto de oblea y maní... algo que cambiará el mundo del chocolate."
  },
  {
    levelNumber: 34,
    title: "Nivel 34: Nace la Leyenda de Bon o Bon, 1984",
    year: 1984,
    decadeTitle: "Años 80: La Leyenda Bon o Bon",
    xPercent: 16.3,
    yPercent: 81.5,
    description: "Fulvio Salvador Pagani crea el Bon o Bon: oblea crocante, relleno de crema de maní y chocolate.",
    quote: "Un bombón tan perfecto y accesible que cualquier persona pueda regalarlo cada día con cariño.",
    targetCandies: ["bonobon","aguila","mogul"],
    eraTag: "✨ NACIMIENTO DE BON O BON",
    storyHeadline: "¡Año 1984: Don Fulvio crea la mayor leyenda: Bon o Bon!",
    storyBody: "En 1984, Fulvio Pagani concreta su gran sueño: democratizar el consumo de bombones finos. Nace Bon o Bon: dos semiesferas de oblea crocante, generoso relleno de crema de maní y cobertura de chocolate con leche.",
    funFact: "Bon o Bon se transformó en el bombón más vendido de América Latina y se consume en más de 80 países.",
    isSpecialMilestone: true,
    milestoneTitle: "Creación de Bon o Bon: El Gran Hito Mundial"
  },
  {
    levelNumber: 35,
    title: "Nivel 35: Creación de Butter Toffees, 1985",
    year: 1985,
    decadeTitle: "Años 80: Reyes del Toffee",
    xPercent: 17.5,
    yPercent: 84,
    description: "Se lanzan los Butter Toffees, el caramelo suave de leche y manteca líder indiscutido.",
    quote: "La elegancia dorada del mejor caramelo de leche.",
    targetCandies: ["buttertoffe","bonobon","mogul"],
    eraTag: "👑 BUTTER TOFFEES",
    storyHeadline: "¡Año 1985: nacen los emblemáticos Butter Toffees!",
    storyBody: "Inspirados en la tradición confitera inglesa pero elaborados con el insuperable dulce de leche argentino, nacen los Butter Toffees. Su envoltura dorada se convierte en un ícono de distinción.",
    funFact: "Es el caramelo relleno más elegido por los adultos y se exporta a más de 70 países.",
    isSpecialMilestone: true,
    milestoneTitle: "Lanzamiento de Butter Toffees"
  },
  {
    levelNumber: 36,
    title: "Nivel 36: Complejo Agroindustrial Cuyo, 1986",
    year: 1986,
    decadeTitle: "Años 80: Complejo Agroindustrial Cuyo",
    xPercent: 21.3,
    yPercent: 84.3,
    description: "Inauguración de plantas en San Juan y Mendoza para producción de pulpas y tomates.",
    quote: "El sol cuyano nutre los frutos que enriquecen nuestros dulces y alimentos.",
    targetCandies: ["buttertoffe","bonobon","caramelo_1951"],
    eraTag: "☀️ AGROINDUSTRIA CUYO",
    storyHeadline: "¡Año 1986: plantas en San Juan y Mendoza!",
    storyBody: "Arcor se expande a la región de Cuyo para cultivar y procesar tomates, duraznos, peras y ciruelas. Nace la división agroindustrial que asegura materias primas de excelencia.",
    funFact: "Cuyo provee las pulpas naturales para las mermeladas y rellenos de toda la compañía.",
    isSpecialMilestone: false
  },
  {
    levelNumber: 37,
    title: "Nivel 37: Robotización de Bon o Bon, 1987",
    year: 1987,
    decadeTitle: "Años 80: Líneas Robotizadas",
    xPercent: 25,
    yPercent: 84.5,
    description: "Instalación de túneles de enfriamiento y dosificadoras de alta velocidad.",
    quote: "Tecnología de precisión para que cada Bon o Bon sea una obra de arte idéntica.",
    targetCandies: ["bonobon","buttertoffe"],
    eraTag: "🤖 ROBOTIZACIÓN BON O BON",
    storyHeadline: "¡Año 1987: millones de Bon o Bon por día!",
    storyBody: "Para abastecer el furor del mercado, se instalan líneas automatizadas continuas que dosifican la crema de maní y bañan millones de bombones por jornada.",
    funFact: "En 1987 la planta de Arroyito producía más de 3 millones de Bon o Bon por día.",
    isSpecialMilestone: false
  },
  {
    levelNumber: 38,
    title: "Nivel 38: Expansión en Bragança Paulista, 1988",
    year: 1988,
    decadeTitle: "Años 80: Arcor Brasil",
    xPercent: 28.3,
    yPercent: 83.6,
    description: "Modernización y ampliación de la planta de golosinas en el estado de San Pablo.",
    quote: "La dulzura argentina cruza la frontera para conquistar al público brasileño.",
    targetCandies: ["bonobon","mogul","caramelo_1951"],
    eraTag: "🇧🇷 ARCOR DO BRASIL",
    storyHeadline: "¡Año 1988: gran ampliación de la planta en Brasil!",
    storyBody: "Arcor do Brasil amplía su capacidad instalada en Bragança Paulista, comenzando a fabricar localmente caramelos duros, pirulitos y bombones para el enorme mercado brasileño.",
    funFact: "Hoy Arcor es una de las marcas más reconocidas y tradicionales del mercado de dulces de Brasil.",
    isSpecialMilestone: false,
    hint: "Los distribuidores y comerciantes planean algo especial... una golosina a cambio de un gesto de amor."
  },
  {
    levelNumber: 39,
    title: "Nivel 39: Una Golosina por un Beso, 1989",
    year: 1989,
    decadeTitle: "Años 80: Semana de la Dulzura",
    xPercent: 34.8,
    yPercent: 81.9,
    description: "Se institucionaliza la Semana de la Dulzura y se adquiere Alimentos Indal en Chile.",
    quote: "Una golosina por un beso: cuando el cariño popular se transforma en tradición viva.",
    targetCandies: ["bonobon","buttertoffe","mogul"],
    eraTag: "💋 SEMANA DE LA DULZURA",
    storyHeadline: "¡Año 1989: nace la Semana de la Dulzura y llegada a Chile!",
    storyBody: "En julio de 1989, Arcor impulsa junto a los distribuidores la 'Semana de la Dulzura' con el lema 'Una golosina por un beso'. El mismo año adquiere Alimentos Indal S.A. en Chile.",
    funFact: "La Semana de la Dulzura se convirtió en una de las costumbres populares más arraigadas del país cada 1 al 7 de julio.",
    isSpecialMilestone: true,
    milestoneTitle: "Semana de la Dulzura y Alimentos Indal (Chile)"
  },
  {
    levelNumber: 40,
    title: "Nivel 40: El Legado Imborrable, 1990",
    year: 1990,
    decadeTitle: "Años 90: El Legado de Don Fulvio",
    xPercent: 38,
    yPercent: 81,
    description: "Homenaje a Don Fulvio Salvador Pagani. Su visión fundacional guía el futuro.",
    quote: "Los hombres pasan, pero las obras fundadas con amor y rectitud permanecen para siempre.",
    targetCandies: ["bonobon","buttertoffe","aguila"],
    eraTag: "🕊️ LEGADO DE DON FULVIO",
    storyHeadline: "¡Año 1990: el legado eterno de Fulvio Pagani!",
    storyBody: "Tras el fallecimiento de Don Fulvio Pagani en 1990, la compañía reafirma su compromiso con los valores de honestidad, trabajo en equipo y pasión por el crecimiento de la comunidad.",
    funFact: "Don Fulvio dejó sentadas las bases de un modelo de gestión basado en la reinversión constante de utilidades.",
    isSpecialMilestone: false
  },
  {
    levelNumber: 41,
    title: "Nivel 41: Creación de Fundación Arcor, 1991",
    year: 1991,
    decadeTitle: "Años 90: Compromiso Social",
    xPercent: 40.1,
    yPercent: 80.5,
    description: "Nace la Fundación Arcor para promover los derechos de la niñez y la educación.",
    quote: "La verdadera grandeza de una empresa se mide por la felicidad de sus niños.",
    targetCandies: ["bonobon","mogul","caramelo_1951"],
    eraTag: "🌱 FUNDACIÓN ARCOR",
    storyHeadline: "¡Año 1991: nace la Fundación Arcor!",
    storyBody: "Se formaliza la Fundación Arcor, canalizando programas educativos, becas escolares y proyectos de nutrición infantil para miles de comunidades vulnerables de toda América Latina.",
    funFact: "La Fundación Arcor ha beneficiado a más de 5 millones de niños y niñas desde su creación.",
    isSpecialMilestone: true,
    milestoneTitle: "Creación de la Fundación Arcor",
    hint: "Miami será la puerta de entrada a los supermercados de América del Norte."
  },
  {
    levelNumber: 42,
    title: "Nivel 42: Arcor USA en Miami, 1992",
    year: 1992,
    decadeTitle: "Años 90: Arcor USA",
    xPercent: 45,
    yPercent: 79.3,
    description: "Inauguración de las oficinas comerciales de Arcor USA en Miami, Florida.",
    quote: "De Arroyito al corazón del mercado norteamericano.",
    targetCandies: ["bonobon","buttertoffe"],
    eraTag: "🇺🇸 ARCOR USA",
    storyHeadline: "¡Año 1992: sede comercial propia en Miami!",
    storyBody: "Arcor abre su sede propia en Miami para coordinar la importación y logística de golosinas en las grandes cadenas minoristas de Estados Unidos y Canadá.",
    funFact: "En Miami se adaptaron formatos especiales de Bon o Bon para Halloween y San Valentín.",
    isSpecialMilestone: false,
    hint: "La empresa de chocolate más antigua de Argentina (desde 1880) se sumará a la familia Arcor junto al nuevo liderazgo de Luis Pagani."
  },
  {
    levelNumber: 43,
    title: "Nivel 43: Luis Pagani, Águila y Nace Cofler, 1993",
    year: 1993,
    decadeTitle: "Años 90: La Era Luis Pagani",
    xPercent: 49.9,
    yPercent: 78,
    description: "Luis A. Pagani asume la presidencia. Arcor adquiere Águila Saint (1880) y crea las tabletas Cofler.",
    quote: "La felicidad no tiene horario: se parte y se comparte.",
    targetCandies: ["cofler","aguila","bonobon"],
    eraTag: "👑 ERA LUIS PAGANI Y COFLER",
    storyHeadline: "¡Año 1993: Luis Pagani presidente, unión con Águila y nace Cofler!",
    storyBody: "Luis A. Pagani asume la presidencia del Grupo. Se adquiere la mítica marca Chocolates Águila (fundada en 1880) y se lanza Cofler con su lema 'La felicidad se parte y se comparte'.",
    funFact: "Águila aportó más de un siglo de maestría pastelera y el chocolate taza más famoso de la historia argentina.",
    isSpecialMilestone: true,
    milestoneTitle: "Presidencia de Luis Pagani, Chocolates Águila y Cofler"
  },
  {
    levelNumber: 44,
    title: "Nivel 44: Mega-Planta Colonia Caroya, 1994",
    year: 1994,
    decadeTitle: "Años 90: Planta Colonia Caroya",
    xPercent: 52,
    yPercent: 77.5,
    description: "Inauguración de la planta modelo de chocolates en Colonia Caroya, Córdoba.",
    quote: "Tecnología de última generación al servicio del mejor chocolate artesanal.",
    targetCandies: ["cofler","aguila"],
    eraTag: "🍫 COLONIA CAROYA",
    storyHeadline: "¡Año 1994: se inaugura la planta modelo de chocolates!",
    storyBody: "Se inaugura el complejo industrial de Colonia Caroya, una de las plantas de chocolatería más modernas y avanzadas del planeta, con líneas climatizadas de atmósfera controlada.",
    funFact: "La planta de Colonia Caroya produce millones de tabletas Cofler, Águila y coberturas finas al día.",
    isSpecialMilestone: false
  },
  {
    levelNumber: 45,
    title: "Nivel 45: Expansión a Perú, Colombia y Ecuador, 1995",
    year: 1995,
    decadeTitle: "Años 90: Región Andina",
    xPercent: 53,
    yPercent: 77.3,
    description: "Apertura de filiales comerciales en Lima, Bogotá y Guayaquil.",
    quote: "Llevar la dulzura a cada rincón de la cordillera andina.",
    targetCandies: ["bonobon","cofler","mogul"],
    eraTag: "🏔️ REGIÓN ANDINA",
    storyHeadline: "¡Año 1995: filiales en Lima, Bogotá y Guayaquil!",
    storyBody: "Arcor desembarca con oficinas directas en los países andinos, posicionando a Bon o Bon y Mogul como las marcas preferidas de las familias de la región.",
    funFact: "En Perú, el Bon o Bon se convirtió rápidamente en el bombón más obsequiado en el Día de la Madre y San Valentín.",
    isSpecialMilestone: false,
    hint: "Confites crujientes multicolores con centro de puro chocolate se están preparando..."
  },
  {
    levelNumber: 46,
    title: "Nivel 46: Nacimiento de Rocklets, 1996",
    year: 1996,
    decadeTitle: "Años 90: Explosión Rocklets",
    xPercent: 55.5,
    yPercent: 76.8,
    description: "Lanzamiento de Rocklets, los confites de chocolate multicolores más famosos.",
    quote: "Colores divertidos por fuera, puro chocolate crujiente por dentro.",
    targetCandies: ["rocklets","cofler","bonobon"],
    eraTag: "🌈 REVOLUCIÓN ROCKLETS",
    storyHeadline: "¡Año 1996: nacen los confites multicolores Rocklets!",
    storyBody: "Arcor presenta Rocklets: confites de chocolate con leche recubiertos por una capa crujiente de vivos colores. Con divertidos personajes animados, se vuelven un éxito fulminante.",
    funFact: "El proceso de confitado requiere girar bombos de cobre durante horas para lograr el brillo perfecto sin colorantes artificiales.",
    isSpecialMilestone: true,
    milestoneTitle: "Lanzamiento de Rocklets"
  },
  {
    levelNumber: 47,
    title: "Nivel 47: Mega-Planta Cartocor en Luján, 1997",
    year: 1997,
    decadeTitle: "Años 90: Cartocor Luján",
    xPercent: 58,
    yPercent: 76.2,
    description: "Inauguración de la mayor planta de cartón corrugado de Sudamérica en Luján.",
    quote: "La fortaleza del packaging nacional respaldando el comercio de exportación.",
    targetCandies: ["rocklets","cofler","buttertoffe"],
    eraTag: "📦 CARTOCOR LUJÁN",
    storyHeadline: "¡Año 1997: se inaugura Cartocor Luján!",
    storyBody: "Cartocor inaugura su planta de Luján, provincia de Buenos Aires, con corrugadoras alemanas de última generación capaces de producir millones de metros cuadrados de cajas diarias.",
    funFact: "Cartocor Luján es una de las plantas de embalajes más grandes y eficientes de América Latina.",
    isSpecialMilestone: false,
    hint: "En Chile, la histórica empresa de los chocolates Sapito y Nikolo negocia unirse al Grupo Arcor."
  },
  {
    levelNumber: 48,
    title: "Nivel 48: Adquisición de Dos en Uno (Chile), 1998",
    year: 1998,
    decadeTitle: "Años 90: Unión Chilena",
    xPercent: 59,
    yPercent: 76,
    description: "Arcor adquiere Dos en Uno en Chile, sumando marcas legendarias como Sapito y Nikolo.",
    quote: "Sumar leyendas trasandinas para liderar la industria de golosinas en el Pacífico.",
    targetCandies: ["bonobon","rocklets","cofler"],
    eraTag: "🇨🇱 DOS EN UNO CHILE",
    storyHeadline: "¡Año 1998: Arcor adquiere Dos en Uno en Chile!",
    storyBody: "En una de las adquisiciones más resonantes de la década, Arcor adquiere la empresa chilena Dos en Uno, consolidando su liderazgo absoluto en golosinas y chocolates en el Cono Sur.",
    funFact: "La operación sumó emblemáticas marcas chilenas como Sapito, Nikolo y Chocman al portafolio de Arcor.",
    isSpecialMilestone: true,
    milestoneTitle: "Adquisición de Dos en Uno (Chile)"
  },
  {
    levelNumber: 49,
    title: "Nivel 49: La Fábrica Más Moderna del Mundo, 1999",
    year: 1999,
    decadeTitle: "Años 90: Bragança Paulista Modelo",
    xPercent: 60,
    yPercent: 73.8,
    description: "Inauguración de la mega-planta de caramelos en Bragança Paulista, Brasil.",
    quote: "Ingeniería de vanguardia para abastecer a más de doscientos millones de personas.",
    targetCandies: ["buttertoffe","bonobon","rocklets"],
    eraTag: "🏭 VANGUARDIA BRAGANÇA",
    storyHeadline: "¡Año 1999: planta modelo de golosinas en Brasil!",
    storyBody: "Arcor culmina el siglo XX inaugurando en Bragança Paulista una de las fábricas de caramelos más tecnológicas del mundo, con robots de envasado y trazabilidad digital completa.",
    funFact: "La planta fue premiada internacionalmente por sus estándares de higiene, robótica y ahorro energético.",
    isSpecialMilestone: false,
    hint: "El nuevo milenio llega y con él se festejará medio siglo de historia viva: los 50 años de Arcor."
  },
  {
    levelNumber: 50,
    title: "Nivel 50: Desembarco en los Cinco Continentes, 2000",
    year: 2000,
    decadeTitle: "Años 2000: El Nuevo Milenio",
    xPercent: 61,
    yPercent: 71.5,
    description: "Al comenzar el nuevo siglo, Arcor exporta a más de 80 países en los 5 continentes.",
    quote: "El nuevo milenio nos encuentra llevando dulzura a cada rincón de la Tierra.",
    targetCandies: ["bonobon","rocklets","cofler","buttertoffe"],
    eraTag: "🌍 NUEVO MILENIO",
    storyHeadline: "¡Año 2000: Arcor recibe el nuevo milenio en 80 países!",
    storyBody: "Al dar la bienvenida al año 2000, las golosinas de Arroyito se disfrutan en América, Europa, Asia, África y Oceanía. Se consolidan acuerdos de distribución en Japón y Medio Oriente.",
    funFact: "El Bon o Bon en Japón es considerado un bombón gourmet de altísima categoría para obsequiar.",
    isSpecialMilestone: false,
    hint: "En 2001 Arroyito se vestirá de fiesta dorada: se cumplen 50 años desde la primera paila de 1951."
  },
  {
    levelNumber: 51,
    title: "Nivel 51: 50 Años de Historia (Cincuentenario), 2001",
    year: 2001,
    decadeTitle: "Años 2000: 50° Aniversario",
    xPercent: 61.4,
    yPercent: 69.9,
    description: "Festejo de los 50 años de vida de Arcor: medio siglo de esfuerzo pionero y amistad.",
    quote: "50 años transformando el trabajo honesto y la fe en un coloso de categoría mundial.",
    targetCandies: ["bonobon","cofler","rocklets","aguila"],
    eraTag: "⭐ 50° ANIVERSARIO",
    storyHeadline: "¡Año 2001: Arcor celebra su Cincuentenario (50 Años)! ",
    storyBody: "Medio siglo después de encender aquella primera paila artesanal en 1951, Arcor celebra sus 50 años como la empresa número 1 en golosinas del continente, con miles de trabajadores.",
    funFact: "En Arroyito se erigió el monumento al fundador y se inauguró el Museo Histórico de la empresa.",
    isSpecialMilestone: true,
    milestoneTitle: "Cincuentenario de Arcor (1951-2001)"
  },
  {
    levelNumber: 52,
    title: "Nivel 52: Oficinas en México y España, 2002",
    year: 2002,
    decadeTitle: "Años 2000: México y Europa",
    xPercent: 62.1,
    yPercent: 66.6,
    description: "Apertura de representaciones comerciales directas en Ciudad de México y Barcelona.",
    quote: "Acercar la dulzura a los mercados más dinámicos de habla hispana.",
    targetCandies: ["bonobon","buttertoffe","rocklets"],
    eraTag: "🇲🇽 MÉXICO Y ESPAÑA",
    storyHeadline: "¡Año 2002: filiales en Ciudad de México y Barcelona!",
    storyBody: "Arcor abre oficinas en México y Europa para atender con personal propio a las grandes cadenas de hipermercados y tiendas de conveniencia internacionales.",
    funFact: "En México, los Butter Toffees y Bon o Bon lograron un éxito masivo en tiendas OXXO y autoservicios.",
    isSpecialMilestone: false
  },
  {
    levelNumber: 53,
    title: "Nivel 53: Cadena Logística Global, 2003",
    year: 2003,
    decadeTitle: "Años 2000: Logística Global",
    xPercent: 62.5,
    yPercent: 65,
    description: "Implementación de sistemas SAP integrados para trazabilidad global de pedidos.",
    quote: "La tecnología digital asegura que ningún quiosco se quede sin su golosina favorita.",
    targetCandies: ["cofler","bonobon","mogul"],
    eraTag: "💻 LOGÍSTICA DIGITAL",
    storyHeadline: "¡Año 2003: trazabilidad digital de punta a punta!",
    storyBody: "Se digitalizan los almacenes y centros de distribución con códigos inteligentes y trazabilidad satelital en las flotas de transporte en toda América.",
    funFact: "Cada lote de bombones puede rastrearse desde el saco de cacao de origen hasta el quiosco final.",
    isSpecialMilestone: false,
    hint: "Dos gigantes de la alimentación preparan la unión galletera más grande de América del Sur: Arcor y Bagley."
  },
  {
    levelNumber: 54,
    title: "Nivel 54: Nace Bagley Latinoamérica, 2004",
    year: 2004,
    decadeTitle: "Años 2000: Alianza Bagley",
    xPercent: 63.9,
    yPercent: 64.6,
    description: "Alianza con el Grupo Danone para crear la empresa galletera más grande de Sudamérica.",
    quote: "Dos marcas con historia se unen para acompañar las meriendas de millones de familias.",
    targetCandies: ["buttertoffe","bonobon","rocklets"],
    eraTag: "🍪 ALIANZA BAGLEY",
    storyHeadline: "¡Año 2004: nace Bagley Latinoamérica!",
    storyBody: "Arcor y el Grupo Danone sellan una alianza histórica creando Bagley Latinoamérica S.A. Clásicos entrañables de la merienda como Chocolinas, Criollitas, Opera, Rumba y Sonrisas se unen a la familia.",
    funFact: "Con esta alianza, Arcor se convirtió en el mayor productor de galletitas de América del Sur.",
    isSpecialMilestone: true,
    milestoneTitle: "Creación de Bagley Latinoamérica S.A.",
    hint: "En 2005 Arcor sumará las mermeladas de La Campagnola y debutará en el tentador mundo de los helados."
  },
  {
    levelNumber: 55,
    title: "Nivel 55: La Campagnola y Helados Arcor, 2005",
    year: 2005,
    decadeTitle: "Años 2000: La Campagnola y Helados",
    xPercent: 66.6,
    yPercent: 63.9,
    description: "Se adquiere La Campagnola (conservas, mermeladas) y se lanza la división de Helados Arcor.",
    quote: "Desde el postre helado en el verano hasta la mejor mermelada en el desayuno de cada día.",
    targetCandies: ["bonobon","cofler","rocklets","mogul"],
    eraTag: "🍦 LA CAMPAGNOLA Y HELADOS",
    storyHeadline: "¡Año 2005: compra de La Campagnola y nacimiento de Helados Arcor!",
    storyBody: "En 2005 Arcor adquiere Benvenuto S.A.C.I. (La Campagnola), líder en mermeladas, tomates y conservas. El mismo año lanza Helados Arcor, llevando a Bon o Bon, Cofler y Mogul al formato helado.",
    funFact: "El helado Bon o Bon se convirtió en el helado de quiosco más vendido de Argentina en su primera temporada.",
    isSpecialMilestone: true,
    milestoneTitle: "Adquisición de La Campagnola y Helados Arcor"
  },
  {
    levelNumber: 56,
    title: "Nivel 56: Alianza Productiva con Bimbo (México), 2006",
    year: 2006,
    decadeTitle: "Años 2000: Alianza Bimbo",
    xPercent: 68,
    yPercent: 63.5,
    description: "Joint-venture con el Grupo Bimbo para producir dulces en México.",
    quote: "La unión de líderes para alimentar a toda América Latina.",
    targetCandies: ["bonobon","buttertoffe"],
    eraTag: "🇲🇽 ALIANZA BIMBO",
    storyHeadline: "¡Año 2006: alianza estratégica con Grupo Bimbo!",
    storyBody: "Arcor y el gigante panificador mexicano Bimbo crean una empresa conjunta para fabricar golosinas y chocolates en territorio azteca, potenciando la llegada a millones de consumidores.",
    funFact: "Esta alianza combinó la capacidad confitera de Arcor con la inmensa red de distribución de Bimbo.",
    isSpecialMilestone: false
  },
  {
    levelNumber: 57,
    title: "Nivel 57: Nueva Planta de Jarabe de Maíz, 2007",
    year: 2007,
    decadeTitle: "Años 2000: Molienda de Jarabe de Maíz",
    xPercent: 69.6,
    yPercent: 63.9,
    description: "Ampliación de la planta de molienda húmeda para jarabes de fructosa en Arroyito.",
    quote: "El maíz argentino convertido en la energía dulce que abastece a la industria.",
    targetCandies: ["caramelo_1951","mogul"],
    eraTag: "🌽 JARABE DE MAÍZ",
    storyHeadline: "¡Año 2007: ampliación de jarabes de fructosa!",
    storyBody: "Se inaugura la moderna línea de jarabes de maíz de alta fructosa (JMAF) en Arroyito, insumo clave para bebidas, yogures y panificados de las principales marcas del país.",
    funFact: "La molienda de maíz de Arcor procesa cientos de miles de toneladas anuales de granos cordobeses.",
    isSpecialMilestone: false
  },
  {
    levelNumber: 58,
    title: "Nivel 58: Envases Flexibles Converflex, 2008",
    year: 2008,
    decadeTitle: "Años 2000: Converflex y Packaging Verde",
    xPercent: 72.9,
    yPercent: 64.6,
    description: "Desarrollo de empaques reciclables y reducción de espesor plástico en Converflex.",
    quote: "Cuidar la frescura del producto cuidando al mismo tiempo la naturaleza.",
    targetCandies: ["buttertoffe","rocklets"],
    eraTag: "♻️ PACKAGING VERDE",
    storyHeadline: "¡Año 2008: packaging sustentable con Converflex!",
    storyBody: "Converflex, la unidad de envases flexibles del grupo, introduce tintas al agua y materiales biodegradables para envoltorios de caramelos, galletas y chocolates.",
    funFact: "Se logró reducir en un 15% el uso de plásticos vírgenes en los envoltorios de golosinas.",
    isSpecialMilestone: false
  },
  {
    levelNumber: 59,
    title: "Nivel 59: Filial Comercial en Sudáfrica, 2009",
    year: 2009,
    decadeTitle: "Años 2000: África Austral",
    xPercent: 74.5,
    yPercent: 65,
    description: "Apertura de la oficina comercial en Johannesburgo, Sudáfrica.",
    quote: "Llevar la bandera dulce argentina al continente africano.",
    targetCandies: ["bonobon","buttertoffe"],
    eraTag: "🇿🇦 SUDÁFRICA",
    storyHeadline: "¡Año 2009: desembarco en Johannesburgo, Sudáfrica!",
    storyBody: "Arcor abre su primera oficina comercial en el continente africano, coordinando las ventas de Bon o Bon y caramelos en Sudáfrica, Angola, Mozambique y países vecinos.",
    funFact: "En Angola y Sudáfrica el Bon o Bon se convirtió en un verdadero fenómeno cultural y de consumo.",
    isSpecialMilestone: false,
    hint: "En 2010 Arcor formalizará su compromiso más profundo: la Política de Sustentabilidad a largo plazo."
  },
  {
    levelNumber: 60,
    title: "Nivel 60: Política de Sustentabilidad (PSA), 2010",
    year: 2010,
    decadeTitle: "Años 2010: Sustentabilidad Arcor",
    xPercent: 75.9,
    yPercent: 65.9,
    description: "Lanzamiento formal de la Política de Sustentabilidad Arcor con metas de agua, energía y nutrición.",
    quote: "El éxito económico solo tiene sentido si genera valor compartido con la sociedad y el planeta.",
    targetCandies: ["bonobon","cofler","rocklets","mogul"],
    eraTag: "🌿 POLÍTICA DE SUSTENTABILIDAD",
    storyHeadline: "¡Año 2010: nace la Política de Sustentabilidad Arcor!",
    storyBody: "Se formaliza la Política de Sustentabilidad con metas cuantificables a 2020: reducción de la huella hídrica, eficiencia energética, uso de energías renovables y fomento de hábitos de vida saludable.",
    funFact: "Arcor fue una de las primeras empresas latinoamericanas en auditar anualmente su balance social y ambiental.",
    isSpecialMilestone: true,
    milestoneTitle: "Lanzamiento de la Política de Sustentabilidad Arcor"
  },
  {
    levelNumber: 61,
    title: "Nivel 61: 60 Años de Historia, 2011",
    year: 2011,
    decadeTitle: "Años 2010: 60 Años",
    xPercent: 78.6,
    yPercent: 67.6,
    description: "Festejo del 60° Aniversario con 40 plantas en funcionamiento en toda América.",
    quote: "Seis décadas de crecimiento constante sin perder la calidez de los orígenes.",
    targetCandies: ["aguila","bonobon","toffee_cubo"],
    eraTag: "⭐ 60 AÑOS",
    storyHeadline: "¡Año 2011: seis décadas de compromiso con el trabajo!",
    storyBody: "Arcor cumple 60 años. Se publican libros conmemorativos sobre la historia industrial de Arroyito y se reconoce a los trabajadores con más de 30 años de servicio en la empresa.",
    funFact: "En 2011 más de 20.000 personas integraban la gran familia de colaboradores del Grupo Arcor.",
    isSpecialMilestone: false
  },
  {
    levelNumber: 62,
    title: "Nivel 62: Conectando con los Quiosqueros, 2012",
    year: 2012,
    decadeTitle: "Años 2010: Quioscos Digitales",
    xPercent: 80,
    yPercent: 68.5,
    description: "Programas de modernización y capacitación para más de 200.000 quioscos de barrio.",
    quote: "El quiosquero de la esquina es el corazón de la alegría barrial.",
    targetCandies: ["rocklets","mogul","cofler"],
    eraTag: "🏪 RED DE QUIOSCOS",
    storyHeadline: "¡Año 2012: homenaje y apoyo a la red de quiosqueros!",
    storyBody: "Arcor implementa planes de apoyo comercial, exhibidores modulares y líneas de financiamiento para los pequeños comerciantes de golosinas de toda Argentina.",
    funFact: "En Argentina existen más de 100.000 quioscos donde las marcas de Arcor tienen presencia indiscutida.",
    isSpecialMilestone: false
  },
  {
    levelNumber: 63,
    title: "Nivel 63: Cogeneración con Biomasa en Arroyito, 2013",
    year: 2013,
    decadeTitle: "Años 2010: Energía Limpia por Biomasa",
    xPercent: 80.9,
    yPercent: 67.1,
    description: "Inauguración de la central termoeléctrica a biomasa de maíz y caña.",
    quote: "Los propios residuos orgánicos se transforman en energía limpia para mover los motores.",
    targetCandies: ["caramelo_1951","toffee_cubo"],
    eraTag: "🌱 ENERGÍA LIMPIA",
    storyHeadline: "¡Año 2013: central de biomasa limpia en Arroyito!",
    storyBody: "Se inaugura la planta de cogeneración eléctrica a partir de subproductos de maíz y bagazo de caña, autoabasteciendo de energía limpia a las plantas de Arroyito e inyectando excedentes a la red pública.",
    funFact: "Esta central evitó la emisión de miles de toneladas de gases de efecto invernadero al año.",
    isSpecialMilestone: false
  },
  {
    levelNumber: 64,
    title: "Nivel 64: 30 Años del Rey Bon o Bon, 2014",
    year: 2014,
    decadeTitle: "Años 2010: 30 Años de Bon o Bon",
    xPercent: 82.6,
    yPercent: 64.4,
    description: "Celebración de las tres décadas de Bon o Bon con ediciones especiales en todo el mundo.",
    quote: "Treinta años uniendo corazones y sacando sonrisas en más de ochenta países.",
    targetCandies: ["bonobon","rocklets"],
    eraTag: "✨ 30 AÑOS BON O BON",
    storyHeadline: "¡Año 2014: tres décadas de Bon o Bon conquistando el mundo!",
    storyBody: "Bon o Bon celebra 30 años desde su invención en 1984. Se lanzan sabores especiales: blanco, chocolate amargo, mousse de limón y cookies & cream.",
    funFact: "Si se apilaran los Bon o Bon producidos en estos 30 años, llegarían varias veces a la Luna.",
    isSpecialMilestone: false,
    hint: "Una histórica alianza con la mayor empresa láctea de Argentina está por concretarse: Mastellone Hermanos."
  },
  {
    levelNumber: 65,
    title: "Nivel 65: Ingreso a Mastellone (La Serenísima), 2015",
    year: 2015,
    decadeTitle: "Años 2010: Alianza Láctea",
    xPercent: 83.5,
    yPercent: 63,
    description: "Inversión estratégica en Mastellone Hermanos para potenciar la cadena láctea nacional.",
    quote: "La unión de dos próceres de la alimentación argentina para fortalecer la lechería nacional.",
    targetCandies: ["buttertoffe","bonobon","aguila"],
    eraTag: "🥛 ALIANZA LA SERENÍSIMA",
    storyHeadline: "¡Año 2015: Arcor invierte en Mastellone Hermanos (La Serenísima)!",
    storyBody: "Arcor sella un acuerdo estratégico de inversión y cooperación con Mastellone Hermanos (La Serenísima), uniendo fuerzas para potenciar la cuenca lechera argentina y la elaboración de lácteos de máxima calidad.",
    funFact: "Esta alianza consolidó la sinergia en la provisión de dulce de leche, leche en polvo y manteca para chocolates y toffees.",
    isSpecialMilestone: true,
    milestoneTitle: "Inversión Estratégica en Mastellone Hermanos (La Serenísima)"
  },
  {
    levelNumber: 66,
    title: "Nivel 66: Compromiso Sin TACC (Libre de Gluten), 2016",
    year: 2016,
    decadeTitle: "Años 2010: Portafolio Sin TACC",
    xPercent: 84.3,
    yPercent: 61,
    description: "Certificación de más de 300 productos aptos para personas celíacas sin costo extra.",
    quote: "Todos los niños y familias merecen disfrutar de la dulzura sin limitaciones de salud.",
    targetCandies: ["mogul","caramelo_1951"],
    eraTag: "🌾 SIN TACC CERTIFICADO",
    storyHeadline: "¡Año 2016: Arcor lidera en alimentos Sin TACC libres de gluten!",
    storyBody: "Arcor certifica líneas exclusivas libres de gluten con el sello Sin TACC en golosinas, chocolates, mermeladas y polvos para postres, garantizando que tengan el mismo precio que los productos comunes.",
    funFact: "Arcor cuenta con uno de los portafolios de golosinas y alimentos sin gluten más extensos de Sudamérica.",
    isSpecialMilestone: false,
    hint: "Cartocor prepara la compra más grande de envases corrugados del país: el Grupo Zucamor."
  },
  {
    levelNumber: 67,
    title: "Nivel 67: Adquisición de Zucamor, 2017",
    year: 2017,
    decadeTitle: "Años 2010: Liderazgo en Packaging",
    xPercent: 86,
    yPercent: 57,
    description: "Cartocor adquiere el 100% de Zucamor, consagrándose líder absoluto en papel y cartón corrugado.",
    quote: "Liderar el embalaje y la economía circular en toda la región.",
    targetCandies: ["rocklets","buttertoffe","cofler"],
    eraTag: "📦 ADQUISICIÓN ZUCAMOR",
    storyHeadline: "¡Año 2017: Cartocor adquiere el Grupo Zucamor!",
    storyBody: "Arcor adquiere el 100% de las acciones de Zucamor S.A., sumando plantas de papel kraft, papel reciclado y envases en varias provincias, convirtiéndose en el fabricante de cartón corrugado más grande del país.",
    funFact: "La adquisición sumó capacidad de reciclado masivo de papel y cartón, impulsando la economía circular.",
    isSpecialMilestone: true,
    milestoneTitle: "Adquisición de Zucamor S.A.",
    hint: "La ciencia médica y farmacéutica de Laboratorios Bagó se unirá con la experiencia en alimentos de Arcor."
  },
  {
    levelNumber: 68,
    title: "Nivel 68: Alianza Bagó y Nutrición Simple, 2018",
    year: 2018,
    decadeTitle: "Años 2010: Alimentos Funcionales",
    xPercent: 86.8,
    yPercent: 55,
    description: "Alianza con Laboratorios Bagó para lanzar la línea Simple de suplementos y nutrición funcional.",
    quote: "Ciencia farmacéutica y placer alimentario para mejorar el bienestar diario de las personas.",
    targetCandies: ["bonobon","mogul","cofler"],
    eraTag: "💊 ALIANZA SIMPLE BAGÓ",
    storyHeadline: "¡Año 2018: Arcor y Bagó crean la línea Simple!",
    storyBody: "Se unen dos de los laboratorios y empresas argentinas más prestigiosas para crear 'Simple': gomitas y pastillas con vitaminas, calcio, fibra y colágeno para cuidar la salud de forma rica y práctica.",
    funFact: "Simple combinó la rigurosidad científica de Bagó con el inigualable sabor y textura de las gomitas Mogul.",
    isSpecialMilestone: true,
    milestoneTitle: "Alianza con Laboratorios Bagó y Línea Simple"
  },
  {
    levelNumber: 69,
    title: "Nivel 69: Fondo de Innovación Kamay Ventures, 2019",
    year: 2019,
    decadeTitle: "Años 2010: Kamay Ventures",
    xPercent: 87.6,
    yPercent: 52.9,
    description: "Lanzamiento del fondo corporativo Kamay Ventures para impulsar startups agroalimentarias.",
    quote: "Invertir en los jóvenes emprendedores de hoy para inventar la alimentación de mañana.",
    targetCandies: ["rocklets","bonobon","aguila"],
    eraTag: "🚀 KAMAY VENTURES",
    storyHeadline: "¡Año 2019: fondo de inversión e innovación Kamay Ventures!",
    storyBody: "Arcor y Coca-Cola unen fuerzas para fundar Kamay Ventures, un fondo de capital de riesgo para acelerar proyectos de inteligencia artificial, biotecnología agrícola y reciclaje en Latinoamérica.",
    funFact: "Kamay Ventures ha impulsado decenas de emprendimientos de agrotecnología y logística sustentable en la región.",
    isSpecialMilestone: false
  },
  {
    levelNumber: 70,
    title: "Nivel 70: La Fábrica Solidaria, 2020",
    year: 2020,
    decadeTitle: "Años 2020: Compromiso y Solidaridad",
    xPercent: 89.2,
    yPercent: 48.6,
    description: "Operación ininterrumpida durante la pandemia para abastecer alimentos y donaciones masivas.",
    quote: "En los momentos más difíciles, nuestro deber es alimentar a la patria sin descanso.",
    targetCandies: ["caramelo_1951","bonobon","toffee_cubo"],
    eraTag: "❤️ SOLIDARIDAD Y SALUD",
    storyHeadline: "¡Año 2020: Arcor no se detiene y redobla su solidaridad!",
    storyBody: "Durante la crisis sanitaria mundial, los trabajadores de Arcor mantuvieron activas las plantas como servicio esencial, donando millones de raciones de alimentos a comedores comunitarios y hospitales.",
    funFact: "Se implementaron protocolos sanitarios de máxima seguridad cuidando la salud de toda la comunidad fabril.",
    isSpecialMilestone: true,
    milestoneTitle: "Compromiso Sustentable 100% Renovable",
    hint: "En 2021 se festejarán 70 años de historia ininterrumpida desde aquel 5 de julio de 1951."
  },
  {
    levelNumber: 71,
    title: "Nivel 71: 70 Años Creando Sonrisas, 2021",
    year: 2021,
    decadeTitle: "Años 2020: 70 Años de Historia",
    xPercent: 90,
    yPercent: 46.5,
    description: "Celebración de las siete décadas de Arcor con presencia global en más de 100 países.",
    quote: "70 años de sueños compartidos, desde el modesto taller de Arroyito hasta los cinco continentes.",
    targetCandies: ["bonobon","cofler","rocklets","aguila","buttertoffe"],
    eraTag: "⭐ 70° ANIVERSARIO",
    storyHeadline: "¡Año 2021: Arcor cumple 70 años haciendo historia!",
    storyBody: "El Grupo Arcor conmemora sus 70 años de vida. De aquella primera paila artesanal a más de 40 plantas industriales en Argentina, Brasil, Chile, Perú y México, exportando a más de 100 países.",
    funFact: "El libro del 70° Aniversario recopiló testimonios de tres generaciones de trabajadores de Arroyito.",
    isSpecialMilestone: true,
    milestoneTitle: "70° Aniversario de Arcor (1951-2021)",
    hint: "El mapa se amplía hacia ultramar... la primera fábrica de Arcor en el continente africano abrirá sus puertas."
  },
  {
    levelNumber: 72,
    title: "Nivel 72: Primera Planta en África (Angola), 2022",
    year: 2022,
    decadeTitle: "Años 2020: Hito en África",
    xPercent: 91.3,
    yPercent: 43.3,
    description: "Inauguración de la planta industrial en Luanda, Angola, en sociedad con el Grupo Webcor.",
    quote: "La bandera industrial de Arcor flamea por primera vez con planta propia en el suelo africano.",
    targetCandies: ["bonobon","buttertoffe","rocklets"],
    eraTag: "🇦🇴 PLANTA EN ÁFRICA",
    storyHeadline: "¡Año 2022: se inaugura la planta industrial de Luanda, Angola!",
    storyBody: "En junio de 2022, Arcor inaugura su primera fábrica fuera del continente americano en Luanda, Angola, produciendo Bon o Bon y galletitas para abastecer al África subsahariana.",
    funFact: "Esta planta es un hito histórico de la industria alimenticia argentina con tecnología 100% de exportación.",
    isSpecialMilestone: true,
    milestoneTitle: "Inauguración de la Planta Industrial en Luanda, Angola"
  },
  {
    levelNumber: 73,
    title: "Nivel 73: Presidencia de Alfredo Pagani, 2023",
    year: 2023,
    decadeTitle: "Años 2020: Transición Generacional",
    xPercent: 92.5,
    yPercent: 40,
    description: "Alfredo Gustavo Pagani asume la presidencia tras tres décadas de liderazgo de Luis Pagani.",
    quote: "Continuidad en los valores, innovación en el método y pasión inquebrantable por el futuro.",
    targetCandies: ["cofler","bonobon","mogul"],
    eraTag: "👔 LIDERAZGO ALFREDO PAGANI",
    storyHeadline: "¡Año 2023: Alfredo Pagani asume la presidencia del Grupo!",
    storyBody: "Tras 30 años de brillante gestión de Luis Pagani, Alfredo Gustavo Pagani asume la presidencia de la compañía, liderando la modernización digital y el fortalecimiento de los negocios agroindustriales y de packaging.",
    funFact: "La transición ratificó el compromiso familiar y profesional de Arcor con el desarrollo productivo a largo plazo.",
    isSpecialMilestone: false,
    hint: "El comercio digital, la venta directa en casa y la inteligencia artificial transforman el servicio al cliente."
  },
  {
    levelNumber: 74,
    title: "Nivel 74: Arcor en Casa y Agricultura Regenerativa, 2024",
    year: 2024,
    decadeTitle: "Años 2020: Transformación Digital",
    xPercent: 93.3,
    yPercent: 36.8,
    description: "Expansión del e-commerce 'Arcor en Casa' y prácticas de agricultura sustentable regenerativa.",
    quote: "La dulzura que llega directo a la puerta de cada hogar con un solo clic.",
    targetCandies: ["rocklets","bonobon","cofler","mogul"],
    eraTag: "📱 ARCOR EN CASA",
    storyHeadline: "¡Año 2024: digitalización y agricultura regenerativa!",
    storyBody: "Arcor potencia su plataforma digital directa al consumidor 'Arcor en Casa', combinada con programas de agricultura regenerativa que enriquecen los suelos de cultivo de maíz y remolacha.",
    funFact: "El 100% del maíz procesado en Arroyito proviene de campos con buenas prácticas agrícolas certificadas.",
    isSpecialMilestone: false,
    hint: "Se acerca la gran fecha cúspide... 75 años de gloria, trabajo y dulzura sin igual: el Nivel 75 te espera."
  },
  {
    levelNumber: 75,
    title: "Nivel 75: 75 Años del Dulce Imperio Global, 2025",
    year: 2025,
    decadeTitle: "Años 2020: Cumbre 75 Años",
    xPercent: 94.2,
    yPercent: 33.5,
    description: "La cumbre de 75 años de historia: desde la primera paila de cobre hasta el liderazgo mundial indiscutido.",
    quote: "Un mundo más dulce no es solo un lema; es nuestro pacto de amor con la humanidad por los próximos 75 años ♡",
    targetCandies: ["bonobon","cofler","rocklets","aguila","buttertoffe","mogul","caramelo_1951"],
    eraTag: "🌟 CUMBRE HISTÓRICA: 75 AÑOS",
    storyHeadline: "¡NIVEL 75: 75 AÑOS DE HISTORIA Y EL FUTURO MÁS DULCE!",
    storyBody: "¡Felicitaciones! Has recorrido los 75 años de historia de Arcor: desde aquel 5 de julio de 1951 en que Don Fulvio encendió la paila de cobre en Arroyito hasta convertir a la empresa en el primer productor mundial de caramelos y coloso multinacional presente en los 5 continentes.",
    funFact: "Arcor cumple 75 años de vida con más de 45 plantas industriales, 21.000 trabajadores y millones de sonrisas cosechadas cada día.",
    isSpecialMilestone: true,
    milestoneTitle: "Cumbre Histórica: 75 Años de Arcor (1951-2026)"
  }
];
